//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMMAND
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public COMMAND()
        {
            this.MSG = new HashSet<MSG>();
        }
    
        public int id { get; set; }
        public System.DateTime datecmd { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<int> idproduit { get; set; }
        public Nullable<int> qte { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PRODUIT PRODUIT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MSG> MSG { get; set; }
    }
}
