//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHFIF3
    {
        public int id { get; set; }
        public System.DateTime datecmd { get; set; }
        public Nullable<int> idclient { get; set; }
        public Nullable<int> qte { get; set; }
        public string libelle { get; set; }
        public int stock { get; set; }
        public string imagep { get; set; }
        public Nullable<double> prix { get; set; }
        public int catlib { get; set; }
    }
}
